name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: expo/expo-github-action@v5
      with:
        expo-version: 3.x
        expo-cache: true
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        ref: master
    - name: Build
      run: |
        npm install
        expo build:web
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        CLEAN: true, 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: web-build
